//
//  Currency.swift
//  iExpense
//
//  Created by Alexey Morozov on 11.03.2022.
//

import Foundation

enum CurrencyCode: String, CustomStringConvertible, CaseIterable {
    case ADP = "ADP"
    case AED = "AED"
    case AFA = "AFA"
    case AFN = "AFN"
    case ALK = "ALK"
    case ALL = "ALL"
    case AMD = "AMD"
    case ANG = "ANG"
    case AOA = "AOA"
    case AOK = "AOK"
    case AON = "AON"
    case AOR = "AOR"
    case ARA = "ARA"
    case ARL = "ARL"
    case ARM = "ARM"
    case ARP = "ARP"
    case ARS = "ARS"
    case ATS = "ATS"
    case AUD = "AUD"
    case AWG = "AWG"
    case AZM = "AZM"
    case AZN = "AZN"
    case BAD = "BAD"
    case BAM = "BAM"
    case BAN = "BAN"
    case BBD = "BBD"
    case BDT = "BDT"
    case BEC = "BEC"
    case BEF = "BEF"
    case BEL = "BEL"
    case BGL = "BGL"
    case BGM = "BGM"
    case BGN = "BGN"
    case BGO = "BGO"
    case BHD = "BHD"
    case BIF = "BIF"
    case BMD = "BMD"
    case BND = "BND"
    case BOB = "BOB"
    case BOL = "BOL"
    case BOP = "BOP"
    case BOV = "BOV"
    case BRB = "BRB"
    case BRC = "BRC"
    case BRE = "BRE"
    case BRL = "BRL"
    case BRN = "BRN"
    case BRR = "BRR"
    case BRZ = "BRZ"
    case BSD = "BSD"
    case BTN = "BTN"
    case BUK = "BUK"
    case BWP = "BWP"
    case BYB = "BYB"
    case BYR = "BYR"
    case BZD = "BZD"
    case CAD = "CAD"
    case CDF = "CDF"
    case CHE = "CHE"
    case CHF = "CHF"
    case CHW = "CHW"
    case CLE = "CLE"
    case CLF = "CLF"
    case CLP = "CLP"
    case CNX = "CNX"
    case CNY = "CNY"
    case COP = "COP"
    case COU = "COU"
    case CRC = "CRC"
    case CSD = "CSD"
    case CSK = "CSK"
    case CUC = "CUC"
    case CUP = "CUP"
    case CVE = "CVE"
    case CYP = "CYP"
    case CZK = "CZK"
    case DDM = "DDM"
    case DEM = "DEM"
    case DJF = "DJF"
    case DKK = "DKK"
    case DOP = "DOP"
    case DZD = "DZD"
    case ECS = "ECS"
    case ECV = "ECV"
    case EEK = "EEK"
    case EGP = "EGP"
    case EQE = "EQE"
    case ERN = "ERN"
    case ESA = "ESA"
    case ESB = "ESB"
    case ESP = "ESP"
    case ETB = "ETB"
    case EUR = "EUR"
    case FIM = "FIM"
    case FJD = "FJD"
    case FKP = "FKP"
    case FRF = "FRF"
    case GBP = "GBP"
    case GEK = "GEK"
    case GEL = "GEL"
    case GHC = "GHC"
    case GHS = "GHS"
    case GIP = "GIP"
    case GMD = "GMD"
    case GNF = "GNF"
    case GNS = "GNS"
    case GQE = "GQE"
    case GRD = "GRD"
    case GTQ = "GTQ"
    case GWE = "GWE"
    case GWP = "GWP"
    case GYD = "GYD"
    case HKD = "HKD"
    case HNL = "HNL"
    case HRD = "HRD"
    case HRK = "HRK"
    case HTG = "HTG"
    case HUF = "HUF"
    case IDR = "IDR"
    case IEP = "IEP"
    case ILP = "ILP"
    case ILR = "ILR"
    case ILS = "ILS"
    case INR = "INR"
    case IQD = "IQD"
    case IRR = "IRR"
    case ISJ = "ISJ"
    case ISK = "ISK"
    case ITL = "ITL"
    case JMD = "JMD"
    case JOD = "JOD"
    case JPY = "JPY"
    case KES = "KES"
    case KGS = "KGS"
    case KHR = "KHR"
    case KMF = "KMF"
    case KPW = "KPW"
    case KRH = "KRH"
    case KRO = "KRO"
    case KRW = "KRW"
    case KWD = "KWD"
    case KYD = "KYD"
    case KZT = "KZT"
    case LAK = "LAK"
    case LBP = "LBP"
    case LKR = "LKR"
    case LRD = "LRD"
    case LSL = "LSL"
    case LSM = "LSM"
    case LTL = "LTL"
    case LTT = "LTT"
    case LUC = "LUC"
    case LUF = "LUF"
    case LUL = "LUL"
    case LVL = "LVL"
    case LVR = "LVR"
    case LYD = "LYD"
    case MAD = "MAD"
    case MAF = "MAF"
    case MCF = "MCF"
    case MDC = "MDC"
    case MDL = "MDL"
    case MGA = "MGA"
    case MGF = "MGF"
    case MKD = "MKD"
    case MKN = "MKN"
    case MLF = "MLF"
    case MMK = "MMK"
    case MNT = "MNT"
    case MOP = "MOP"
    case MRO = "MRO"
    case MTL = "MTL"
    case MTP = "MTP"
    case MUR = "MUR"
    case MVP = "MVP"
    case MVR = "MVR"
    case MWK = "MWK"
    case MXN = "MXN"
    case MXP = "MXP"
    case MXV = "MXV"
    case MYR = "MYR"
    case MZE = "MZE"
    case MZM = "MZM"
    case MZN = "MZN"
    case NAD = "NAD"
    case NGN = "NGN"
    case NIC = "NIC"
    case NIO = "NIO"
    case NLG = "NLG"
    case NOK = "NOK"
    case NPR = "NPR"
    case NZD = "NZD"
    case OMR = "OMR"
    case PAB = "PAB"
    case PEI = "PEI"
    case PEN = "PEN"
    case PES = "PES"
    case PGK = "PGK"
    case PHP = "PHP"
    case PKR = "PKR"
    case PLN = "PLN"
    case PLZ = "PLZ"
    case PTE = "PTE"
    case PYG = "PYG"
    case QAR = "QAR"
    case RHD = "RHD"
    case ROL = "ROL"
    case RON = "RON"
    case RSD = "RSD"
    case RUB = "RUB"
    case RUR = "RUR"
    case RWF = "RWF"
    case SAR = "SAR"
    case SBD = "SBD"
    case SCR = "SCR"
    case SDD = "SDD"
    case SDG = "SDG"
    case SDP = "SDP"
    case SEK = "SEK"
    case SGD = "SGD"
    case SHP = "SHP"
    case SIT = "SIT"
    case SKK = "SKK"
    case SLL = "SLL"
    case SOS = "SOS"
    case SRD = "SRD"
    case SRG = "SRG"
    case STD = "STD"
    case SUR = "SUR"
    case SVC = "SVC"
    case SYP = "SYP"
    case SZL = "SZL"
    case THB = "THB"
    case TJR = "TJR"
    case TJS = "TJS"
    case TMM = "TMM"
    case TMT = "TMT"
    case TND = "TND"
    case TOP = "TOP"
    case TPE = "TPE"
    case TRL = "TRL"
    case TRY = "TRY"
    case TTD = "TTD"
    case TWD = "TWD"
    case TZS = "TZS"
    case UAH = "UAH"
    case UAK = "UAK"
    case UGS = "UGS"
    case UGX = "UGX"
    case USD = "USD"
    case USN = "USN"
    case USS = "USS"
    case UYI = "UYI"
    case UYP = "UYP"
    case UYU = "UYU"
    case UZS = "UZS"
    case VEB = "VEB"
    case VEF = "VEF"
    case VND = "VND"
    case VNN = "VNN"
    case VUV = "VUV"
    case WST = "WST"
    case XAF = "XAF"
    case XAG = "XAG"
    case XAU = "XAU"
    case XBA = "XBA"
    case XBB = "XBB"
    case XBC = "XBC"
    case XBD = "XBD"
    case XCD = "XCD"
    case XDR = "XDR"
    case XEU = "XEU"
    case XFO = "XFO"
    case XFU = "XFU"
    case XOF = "XOF"
    case XPD = "XPD"
    case XPF = "XPF"
    case XPT = "XPT"
    case XRE = "XRE"
    case XTS = "XTS"
    case XXX = "XXX"
    case YDD = "YDD"
    case YER = "YER"
    case YUD = "YUD"
    case YUM = "YUM"
    case YUN = "YUN"
    case YUR = "YUR"
    case ZAL = "ZAL"
    case ZAR = "ZAR"
    case ZMK = "ZMK"
    case ZRN = "ZRN"
    case ZRZ = "ZRZ"
    case ZWL = "ZWL"
    case ZWR = "ZWR"
    case ZWD = "ZWD"
    
    var description : String {
        switch self {
        case .ADP: return "ADP Andorran Peseta"
        case .AED: return "AED United Arab Emirates Dirham"
        case .AFA: return "AFA Afghan Afghani (1927-2002)"
        case .AFN: return "AFN Afghan Afghani"
        case .ALK: return "ALK Albanian Lek (1946-1965)"
        case .ALL: return "ALL Albanian Lek"
        case .AMD: return "AMD Armenian Dram"
        case .ANG: return "ANG Netherlands Antillean Guilder"
        case .AOA: return "AOA Angolan Kwanza"
        case .AOK: return "AOK Angolan Kwanza (1977-1991)"
        case .AON: return "AON Angolan New Kwanza (1990-2000)"
        case .AOR: return "AOR Angolan Readjusted Kwanza (1995-1999)"
        case .ARA: return "ARA Argentine Austral"
        case .ARL: return "ARL Argentine Peso Ley (1970-1983)"
        case .ARM: return "ARM Argentine Peso (1881-1970)"
        case .ARP: return "ARP Argentine Peso (1983-1985)"
        case .ARS: return "ARS Argentine Peso"
        case .ATS: return "ATS Austrian Schilling"
        case .AUD: return "AUD Australian Dollar"
        case .AWG: return "AWG Aruban Florin"
        case .AZM: return "AZM Azerbaijani Manat (1993-2006)"
        case .AZN: return "AZN Azerbaijani Manat"
        case .BAD: return "BAD Bosnia-Herzegovina Dinar (1992-1994)"
        case .BAM: return "BAM Bosnia-Herzegovina Convertible Mark"
        case .BAN: return "BAN Bosnia-Herzegovina New Dinar (1994-1997)"
        case .BBD: return "BBD Barbadian Dollar"
        case .BDT: return "BDT Bangladeshi Taka"
        case .BEC: return "BEC Belgian Franc (convertible)"
        case .BEF: return "BEF Belgian Franc"
        case .BEL: return "BEL Belgian Franc (financial)"
        case .BGL: return "BGL Bulgarian Hard Lev"
        case .BGM: return "BGM Bulgarian Socialist Lev"
        case .BGN: return "BGN Bulgarian Lev"
        case .BGO: return "BGO Bulgarian Lev (1879-1952)"
        case .BHD: return "BHD Bahraini Dinar"
        case .BIF: return "BIF Burundian Franc"
        case .BMD: return "BMD Bermudan Dollar"
        case .BND: return "BND Brunei Dollar"
        case .BOB: return "BOB Bolivian Boliviano"
        case .BOL: return "BOL Bolivian Boliviano (1863-1963)"
        case .BOP: return "BOP Bolivian Peso"
        case .BOV: return "BOV Bolivian Mvdol"
        case .BRB: return "BRB Brazilian New Cruzeiro (1967-1986)"
        case .BRC: return "BRC Brazilian Cruzado (1986-1989)"
        case .BRE: return "BRE Brazilian Cruzeiro (1990-1993)"
        case .BRL: return "BRL Brazilian Real"
        case .BRN: return "BRN Brazilian New Cruzado (1989-1990)"
        case .BRR: return "BRR Brazilian Cruzeiro (1993-1994)"
        case .BRZ: return "BRZ Brazilian Cruzeiro (1942-1967)"
        case .BSD: return "BSD Bahamian Dollar"
        case .BTN: return "BTN Bhutanese Ngultrum"
        case .BUK: return "BUK Burmese Kyat"
        case .BWP: return "BWP Botswanan Pula"
        case .BYB: return "BYB Belarusian New Ruble (1994-1999)"
        case .BYR: return "BYR Belarusian Ruble"
        case .BZD: return "BZD Belize Dollar"
        case .CAD: return "CAD Canadian Dollar"
        case .CDF: return "CDF Congolese Franc"
        case .CHE: return "CHE WIR Euro"
        case .CHF: return "CHF Swiss Franc"
        case .CHW: return "CHW WIR Franc"
        case .CLE: return "CLE Chilean Escudo"
        case .CLF: return "CLF Chilean Unit of Account (UF)"
        case .CLP: return "CLP Chilean Peso"
        case .CNX: return "CNX Chinese People's Bank Dollar"
        case .CNY: return "CNY Chinese Yuan"
        case .COP: return "COP Colombian Peso"
        case .COU: return "COU Colombian Real Value Unit"
        case .CRC: return "CRC Costa Rican Colón"
        case .CSD: return "CSD Serbian Dinar (2002-2006)"
        case .CSK: return "CSK Czechoslovak Hard Koruna"
        case .CUC: return "CUC Cuban Convertible Peso"
        case .CUP: return "CUP Cuban Peso"
        case .CVE: return "CVE Cape Verdean Escudo"
        case .CYP: return "CYP Cypriot Pound"
        case .CZK: return "CZK Czech Republic Koruna"
        case .DDM: return "DDM East German Mark"
        case .DEM: return "DEM German Mark"
        case .DJF: return "DJF Djiboutian Franc"
        case .DKK: return "DKK Danish Krone"
        case .DOP: return "DOP Dominican Peso"
        case .DZD: return "DZD Algerian Dinar"
        case .ECS: return "ECS Ecuadorian Sucre"
        case .ECV: return "ECV Ecuadorian Unit of Constant Value"
        case .EEK: return "EEK Estonian Kroon"
        case .EGP: return "EGP Egyptian Pound"
        case .EQE: return "EEQE null)"
        case .ERN: return "ERN Eritrean Nakfa"
        case .ESA: return "ESA Spanish Peseta (A account)"
        case .ESB: return "ESB Spanish Peseta (convertible account)"
        case .ESP: return "ESP Spanish Peseta"
        case .ETB: return "ETB Ethiopian Birr"
        case .EUR: return "EUR Euro"
        case .FIM: return "FIM Finnish Markka"
        case .FJD: return "FJD Fijian Dollar"
        case .FKP: return "FKP Falkland Islands Pound"
        case .FRF: return "FRF French Franc"
        case .GBP: return "GBP British Pound Sterling"
        case .GEK: return "GEK Georgian Kupon Larit"
        case .GEL: return "GEL Georgian Lari"
        case .GHC: return "GHC Ghanaian Cedi (1979-2007)"
        case .GHS: return "GHS Ghanaian Cedi"
        case .GIP: return "GIP Gibraltar Pound"
        case .GMD: return "GMD Gambian Dalasi"
        case .GNF: return "GNF Guinean Franc"
        case .GNS: return "GNS Guinean Syli"
        case .GQE: return "GQE Equatorial Guinean Ekwele"
        case .GRD: return "GRD Greek Drachma"
        case .GTQ: return "GTQ Guatemalan Quetzal"
        case .GWE: return "GWE Portuguese Guinea Escudo"
        case .GWP: return "GWP Guinea-Bissau Peso"
        case .GYD: return "GYD Guyanaese Dollar"
        case .HKD: return "HKD Hong Kong Dollar"
        case .HNL: return "HNL Honduran Lempira"
        case .HRD: return "HRD Croatian Dinar"
        case .HRK: return "HRK Croatian Kuna"
        case .HTG: return "HTG Haitian Gourde"
        case .HUF: return "HUF Hungarian Forint"
        case .IDR: return "IDR Indonesian Rupiah"
        case .IEP: return "IEP Irish Pound"
        case .ILP: return "ILP Israeli Pound"
        case .ILR: return "ILR Israeli Sheqel (1980-1985)"
        case .ILS: return "ILS Israeli New Sheqel"
        case .INR: return "INR Indian Rupee"
        case .IQD: return "IQD Iraqi Dinar"
        case .IRR: return "IRR Iranian Rial"
        case .ISJ: return "ISJ Icelandic Króna (1918-1981)"
        case .ISK: return "ISK Icelandic Króna"
        case .ITL: return "ITL Italian Lira"
        case .JMD: return "JMD Jamaican Dollar"
        case .JOD: return "JOD Jordanian Dinar"
        case .JPY: return "JPY Japanese Yen"
        case .KES: return "KES Kenyan Shilling"
        case .KGS: return "KGS Kyrgystani Som"
        case .KHR: return "KHR Cambodian Riel"
        case .KMF: return "KMF Comorian Franc"
        case .KPW: return "KPW North Korean Won"
        case .KRH: return "KRH South Korean Hwan (1953-1962)"
        case .KRO: return "KRO South Korean Won (1945-1953)"
        case .KRW: return "KRW South Korean Won"
        case .KWD: return "KWD Kuwaiti Dinar"
        case .KYD: return "KYD Cayman Islands Dollar"
        case .KZT: return "KZT Kazakhstani Tenge"
        case .LAK: return "LAK Laotian Kip"
        case .LBP: return "LBP Lebanese Pound"
        case .LKR: return "LKR Sri Lankan Rupee"
        case .LRD: return "LRD Liberian Dollar"
        case .LSL: return "LSL Lesotho Loti"
        case .LSM: return "LLSM null)"
        case .LTL: return "LTL Lithuanian Litas"
        case .LTT: return "LTT Lithuanian Talonas"
        case .LUC: return "LUC Luxembourgian Convertible Franc"
        case .LUF: return "LUF Luxembourgian Franc"
        case .LUL: return "LUL Luxembourg Financial Franc"
        case .LVL: return "LVL Latvian Lats"
        case .LVR: return "LVR Latvian Ruble"
        case .LYD: return "LYD Libyan Dinar"
        case .MAD: return "MAD Moroccan Dirham"
        case .MAF: return "MAF Moroccan Franc"
        case .MCF: return "MCF Monegasque Franc"
        case .MDC: return "MDC Moldovan Cupon"
        case .MDL: return "MDL Moldovan Leu"
        case .MGA: return "MGA Malagasy Ariary"
        case .MGF: return "MGF Malagasy Franc"
        case .MKD: return "MKD Macedonian Denar"
        case .MKN: return "MKN Macedonian Denar (1992-1993)"
        case .MLF: return "MLF Malian Franc"
        case .MMK: return "MMK Myanma Kyat"
        case .MNT: return "MNT Mongolian Tugrik"
        case .MOP: return "MOP Macanese Pataca"
        case .MRO: return "MRO Mauritanian Ouguiya"
        case .MTL: return "MTL Maltese Lira"
        case .MTP: return "MTP Maltese Pound"
        case .MUR: return "MUR Mauritian Rupee"
        case .MVP: return "MVP Maldivian Rupee"
        case .MVR: return "MVR Maldivian Rufiyaa"
        case .MWK: return "MWK Malawian Kwacha"
        case .MXN: return "MXN Mexican Peso"
        case .MXP: return "MXP Mexican Silver Peso (1861-1992)"
        case .MXV: return "MXV Mexican Investment Unit"
        case .MYR: return "MYR Malaysian Ringgit"
        case .MZE: return "MZE Mozambican Escudo"
        case .MZM: return "MZM Mozambican Metical (1980-2006)"
        case .MZN: return "MZN Mozambican Metical"
        case .NAD: return "NAD Namibian Dollar"
        case .NGN: return "NGN Nigerian Naira"
        case .NIC: return "NIC Nicaraguan Córdoba (1988-1991)"
        case .NIO: return "NIO Nicaraguan Córdoba"
        case .NLG: return "NLG Dutch Guilder"
        case .NOK: return "NOK Norwegian Krone"
        case .NPR: return "NPR Nepalese Rupee"
        case .NZD: return "NZD New Zealand Dollar"
        case .OMR: return "OMR Omani Rial"
        case .PAB: return "PAB Panamanian Balboa"
        case .PEI: return "PEI Peruvian Inti"
        case .PEN: return "PEN Peruvian Nuevo Sol"
        case .PES: return "PES Peruvian Sol (1863-1965)"
        case .PGK: return "PGK Papua New Guinean Kina"
        case .PHP: return "PHP Philippine Peso"
        case .PKR: return "PKR Pakistani Rupee"
        case .PLN: return "PLN Polish Zloty"
        case .PLZ: return "PLZ Polish Zloty (1950-1995)"
        case .PTE: return "PTE Portuguese Escudo"
        case .PYG: return "PYG Paraguayan Guarani"
        case .QAR: return "QAR Qatari Rial"
        case .RHD: return "RHD Rhodesian Dollar"
        case .ROL: return "ROL Romanian Leu (1952-2006)"
        case .RON: return "RON Romanian Leu"
        case .RSD: return "RSD Serbian Dinar"
        case .RUB: return "RUB Russian Ruble"
        case .RUR: return "RUR Russian Ruble (1991-1998)"
        case .RWF: return "RWF Rwandan Franc"
        case .SAR: return "SAR Saudi Riyal"
        case .SBD: return "SBD Solomon Islands Dollar"
        case .SCR: return "SCR Seychellois Rupee"
        case .SDD: return "SDD Sudanese Dinar (1992-2007)"
        case .SDG: return "SDG Sudanese Pound"
        case .SDP: return "SDP Sudanese Pound (1957-1998)"
        case .SEK: return "SEK Swedish Krona"
        case .SGD: return "SGD Singapore Dollar"
        case .SHP: return "SHP Saint Helena Pound"
        case .SIT: return "SIT Slovenian Tolar"
        case .SKK: return "SKK Slovak Koruna"
        case .SLL: return "SLL Sierra Leonean Leone"
        case .SOS: return "SOS Somali Shilling"
        case .SRD: return "SRD Surinamese Dollar"
        case .SRG: return "SRG Surinamese Guilder"
        case .STD: return "STD São Tomé and Príncipe Dobra"
        case .SUR: return "SUR Soviet Rouble"
        case .SVC: return "SVC Salvadoran Colón"
        case .SYP: return "SYP Syrian Pound"
        case .SZL: return "SZL Swazi Lilangeni"
        case .THB: return "THB Thai Baht"
        case .TJR: return "TJR Tajikistani Ruble"
        case .TJS: return "TJS Tajikistani Somoni"
        case .TMM: return "TMM Turkmenistani Manat (1993-2009)"
        case .TMT: return "TMT Turkmenistani Manat"
        case .TND: return "TND Tunisian Dinar"
        case .TOP: return "TOP Tongan Paʻanga"
        case .TPE: return "TPE Timorese Escudo"
        case .TRL: return "TRL Turkish Lira (1922-2005)"
        case .TRY: return "TRY Turkish Lira"
        case .TTD: return "TTD Trinidad and Tobago Dollar"
        case .TWD: return "TWD New Taiwan Dollar"
        case .TZS: return "TZS Tanzanian Shilling"
        case .UAH: return "UAH Ukrainian Hryvnia"
        case .UAK: return "UAK Ukrainian Karbovanets"
        case .UGS: return "UGS Ugandan Shilling (1966-1987)"
        case .UGX: return "UGX Ugandan Shilling"
        case .USD: return "USD US Dollar"
        case .USN: return "USN US Dollar (Next day)"
        case .USS: return "USS US Dollar (Same day)"
        case .UYI: return "UYI Uruguayan Peso (Indexed Units)"
        case .UYP: return "UYP Uruguayan Peso (1975-1993)"
        case .UYU: return "UYU Uruguayan Peso"
        case .UZS: return "UZS Uzbekistan Som"
        case .VEB: return "VEB Venezuelan Bolívar (1871-2008)"
        case .VEF: return "VEF Venezuelan Bolívar"
        case .VND: return "VND Vietnamese Dong"
        case .VNN: return "VNN Vietnamese Dong (1978-1985)"
        case .VUV: return "VUV Vanuatu Vatu"
        case .WST: return "WST Samoan Tala"
        case .XAF: return "XAF CFA Franc BEAC"
        case .XAG: return "XAG Silver"
        case .XAU: return "XAU Gold"
        case .XBA: return "XBA European Composite Unit"
        case .XBB: return "XBB European Monetary Unit"
        case .XBC: return "XBC European Unit of Account (XBC)"
        case .XBD: return "XBD European Unit of Account (XBD)"
        case .XCD: return "XCD East Caribbean Dollar"
        case .XDR: return "XDR Special Drawing Rights"
        case .XEU: return "XEU European Currency Unit"
        case .XFO: return "XFO French Gold Franc"
        case .XFU: return "XFU French UIC-Franc"
        case .XOF: return "XOF CFA Franc BCEAO"
        case .XPD: return "XPD Palladium"
        case .XPF: return "XPF CFP Franc"
        case .XPT: return "XPT Platinum"
        case .XRE: return "XRE RINET Funds"
        case .XTS: return "XTS Testing Currency Code"
        case .XXX: return "XXX Unknown Currency"
        case .YDD: return "YDD Yemeni Dinar"
        case .YER: return "YER Yemeni Rial"
        case .YUD: return "YUD Yugoslavian Hard Dinar (1966-1990)"
        case .YUM: return "YUM Yugoslavian New Dinar (1994-2002)"
        case .YUN: return "YUN Yugoslavian Convertible Dinar (1990-1992)"
        case .YUR: return "YUR Yugoslavian Reformed Dinar (1992-1993)"
        case .ZAL: return "ZAL South African Rand (financial)"
        case .ZAR: return "ZAR South African Rand"
        case .ZMK: return "ZMK Zambian Kwacha"
        case .ZRN: return "ZRN Zairean New Zaire (1993-1998)"
        case .ZRZ: return "ZRZ Zairean Zaire (1971-1993)"
        case .ZWL: return "ZWL Zimbabwean Dollar (2009)"
        case .ZWR: return "ZWR Zimbabwean Dollar (2008)"
        case .ZWD: return "ZWD Zimbabwean Dollar (1980-2008)"
        }
      }
}
